server.port=8081
spring.application.name=functions-sample
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

# Expose all functions individually
spring.cloud.function.scan.enabled=true
spring.cloud.function.definition=sanitizeText;generateEventId;auditEvent;reactiveStreamProcess;reactiveHeartbeatSupplier;reactiveBatchConsumer;asyncSingleProcess;splitAndExpand;processWithHeaders;reactiveMessageProcess;sanitizeAndMask;processOrder
